version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt || true
  build:
    commands:
      - echo Zipping application files...
      - zip -r app.zip app.py appspec.yml scripts/ requirements.txt
artifacts:
  files:
    - app.zip
